a = input("Enter your Name ")
b = input("Enter your Branch ")
c = int(input("Enter your Age "))
d = input("Enter your Collage ")
e = input("Enter your Gender ")
print("Name",a)
print("Branch",b)
print("Age",c)
print("Collage",d)
print("Gender",e)
